name: CI on Pull Request

on:
  pull_request:
    branches: [ main, qa ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install pip
      run: python -m pip install --upgrade pip

    - name: Run tests
      run: |
        cd deployments/modules/aws/lambda/python/
        python -m unittest test_battery_health_monitor.py

    - name: Run pylint
      run: |
        pip install pylint
        pylint deployments/modules/aws/lambda/python/ --fail-under=10

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          ![Alt text](https://i.pinimg.com/1200x/13/ff/49/13ff49773ca9c25ac2116c8bc6c4d2ee.jpg)
          Tests outcome: ${{ steps.tests.outcome }}
          Pylint outcome: ${{ steps.pylint.outcome }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
